# Generated by Django 4.2.23 on 2025-06-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tag',
            new_name='tags',
        ),
    ]
