# Generated by Django 4.2.23 on 2025-06-30 07:01

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.image_upload_path),
        ),
    ]
